# Generated by Django 5.1.4 on 2024-12-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_department_studentid_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='department',
        ),
    ]
